package com.fantasticsource.dynamicstealth.server.ai;

import java.util.ArrayList;

public class EntityAIDefaults
{
    public static ArrayList<String> fearlessDefaults = new ArrayList<>();

    static
    {
        fearlessDefaults.add("player");
        fearlessDefaults.add("zombie");
        fearlessDefaults.add("zombie_villager");
        fearlessDefaults.add("elder_guardian");
        fearlessDefaults.add("husk");
        fearlessDefaults.add("skeleton");
        fearlessDefaults.add("stray");
        fearlessDefaults.add("wither_skeleton");
        fearlessDefaults.add("creeper");
        fearlessDefaults.add("ghast");
        fearlessDefaults.add("slime");
        fearlessDefaults.add("magma_cube");
        fearlessDefaults.add("enderman");
        fearlessDefaults.add("ender_dragon");
        fearlessDefaults.add("wither");
        fearlessDefaults.add("skeleton_horse");
        fearlessDefaults.add("zombie_horse");
        fearlessDefaults.add("blaze");
        fearlessDefaults.add("snowman");
        fearlessDefaults.add("villager_golem");


        //Compat; these should be added absolutely, not conditionally

        fearlessDefaults.add("harvestersnight:harvester");
        fearlessDefaults.add("defiledlands:the_destroyer");
        fearlessDefaults.add("defiledlands:the_mourner");

        fearlessDefaults.add("ebwizardry:skeleton_minion");
        fearlessDefaults.add("ebwizardry:spirit_wolf");
        fearlessDefaults.add("ebwizardry:ice_wraith");
        fearlessDefaults.add("ebwizardry:lightning_wraith");
        fearlessDefaults.add("ebwizardry:shadow_wraith");
        fearlessDefaults.add("ebwizardry:magic_slime");
        fearlessDefaults.add("ebwizardry:spirit_horse");
        fearlessDefaults.add("ebwizardry:phoenix");
        fearlessDefaults.add("ebwizardry:storm_elemental");
        fearlessDefaults.add("ebwizardry:wither_skeleton_minion");
        fearlessDefaults.add("emberroot:rainbowslime");
        fearlessDefaults.add("emberroot:rainbow_golem");
        fearlessDefaults.add("emberroot:hero");
        fearlessDefaults.add("emberroot:creeper");
        fearlessDefaults.add("emberroot:slime");
        fearlessDefaults.add("emberroot:dire_wolf");
        fearlessDefaults.add("emberroot:withercat");
        fearlessDefaults.add("emberroot:enderminy");
        fearlessDefaults.add("emberroot:knight_fallen");
        fearlessDefaults.add("emberroot:fallenmount");
        fearlessDefaults.add("emberroot:rootsonespriteboss");
        fearlessDefaults.add("emberroot:skeleton_frozen");
        fearlessDefaults.add("endreborn:endguard");
        fearlessDefaults.add("endreborn:watcher");
        fearlessDefaults.add("endreborn:endlord");
        fearlessDefaults.add("endreborn:angry_enderman");
        fearlessDefaults.add("endreborn:chronologist");
        fearlessDefaults.add("thermalfoundation:blizz");
        fearlessDefaults.add("thermalfoundation:blitz");
        fearlessDefaults.add("thermalfoundation:basalz");
        fearlessDefaults.add("goblinencounter:goblinking");
        fearlessDefaults.add("nex:gold_golem");
        fearlessDefaults.add("nex:wight");
        fearlessDefaults.add("nex:spinout");
        fearlessDefaults.add("nex:spore_creeper");
        fearlessDefaults.add("nex:ghastling");
        fearlessDefaults.add("nex:bone_spider");
        fearlessDefaults.add("nex:ghast_queen");
        fearlessDefaults.add("nethergoldplus:zombiepigmanwarrior");
        fearlessDefaults.add("primitivemobs:treasure_slime");
        fearlessDefaults.add("primitivemobs:haunted_tool");
        fearlessDefaults.add("primitivemobs:bewitched_tome");
        fearlessDefaults.add("primitivemobs:brain_slime");
        fearlessDefaults.add("primitivemobs:rocket_creeper");
        fearlessDefaults.add("primitivemobs:festive_creeper");
        fearlessDefaults.add("primitivemobs:support_creeper");
        fearlessDefaults.add("primitivemobs:skeleton_warrior");
        fearlessDefaults.add("primitivemobs:blazing_juggernaut");
        fearlessDefaults.add("primitivemobs:void_eye");
        fearlessDefaults.add("varodd:giant_zombie");
        fearlessDefaults.add("natura:nitrocreeper");
        fearlessDefaults.add("betteranimalsplus:feralwolf");
        fearlessDefaults.add("betteranimalsplus:hirschgeist");
        fearlessDefaults.add("defiledlands:shambler");
        fearlessDefaults.add("defiledlands:shambler_twisted");
        fearlessDefaults.add("defiledlands:host");
        fearlessDefaults.add("defiledlands:slime_defiled");
        fearlessDefaults.add("defiledlands:the_destroyer");
        fearlessDefaults.add("defiledlands:the_mourner");
        fearlessDefaults.add("eerieentities:pumpkin_slime");
        fearlessDefaults.add("eerieentities:nether_knight");
        fearlessDefaults.add("eerieentities:cursed_armor");
        fearlessDefaults.add("pvj:pvj_ghost");
        fearlessDefaults.add("pvj:pvj_shade");
        fearlessDefaults.add("pvj:pvj_skeletal_knight");
        fearlessDefaults.add("pvj:pvj_goon");
        fearlessDefaults.add("arcticmobs:wendigo");
        fearlessDefaults.add("demonmobs:rahovart");
        fearlessDefaults.add("desertmobs:cryptzombie");
        fearlessDefaults.add("elementalmobs:spriggan");
        fearlessDefaults.add("elementalmobs:reiver");
        fearlessDefaults.add("elementalmobs:djinn");
        fearlessDefaults.add("elementalmobs:eechetik");
        fearlessDefaults.add("elementalmobs:spectre");
        fearlessDefaults.add("elementalmobs:zephyr");
        fearlessDefaults.add("elementalmobs:tremor");
        fearlessDefaults.add("elementalmobs:geonach");
        fearlessDefaults.add("elementalmobs:wraith");
        fearlessDefaults.add("elementalmobs:vapula");
        fearlessDefaults.add("elementalmobs:grue");
        fearlessDefaults.add("elementalmobs:cinder");
        fearlessDefaults.add("elementalmobs:banshee");
        fearlessDefaults.add("elementalmobs:aegis");
        fearlessDefaults.add("elementalmobs:sylph");
        fearlessDefaults.add("elementalmobs:volcan");
        fearlessDefaults.add("elementalmobs:jengu");
        fearlessDefaults.add("elementalmobs:xaphan");
        fearlessDefaults.add("elementalmobs:argus");
        fearlessDefaults.add("forestmobs:shambler");
        fearlessDefaults.add("infernomobs:gorger");
        fearlessDefaults.add("infernomobs:ignibus");
        fearlessDefaults.add("junglemobs:dawon");
        fearlessDefaults.add("mountainmobs:jabberwock");
        fearlessDefaults.add("mountainmobs:beholder");
        fearlessDefaults.add("plainsmobs:morock");
        fearlessDefaults.add("plainsmobs:feradon");
        fearlessDefaults.add("shadowmobs:geist");
        fearlessDefaults.add("shadowmobs:phantom");
        fearlessDefaults.add("swampmobs:ghoulzombie");
        fearlessDefaults.add("switchbow:littleirongolem");
        fearlessDefaults.add("quark:wraith");
        fearlessDefaults.add("quark:ashen");
    }
}
